export { default as Login } from './Auth/Login/Login'
export { default as Logout } from './Auth/Logout/Logout'
export { default as Signup } from './Auth/Signup/Signup'
export { default as EditProfile } from './EditProfile/EditProfile'
export { default as Home } from './Home/Home'
export { default as Landing } from './Landing/Landing'
export { default as Profile } from './Profile/Profile'
export { default as Post } from './Post/Post'
